#!/usr/bin/env python3
"""
build.py — Solar2DPuzzle platform build manager
================================================

Manages the single-codebase / multi-game publish workflow.
Run from the Solar2DPuzzle/ root folder.

Structure:
  Solar2DPuzzle/
    Get10V3-2026/        ← Solar2D project (open this in Simulator)
    LineConnect-2026/    ← next game
    PublishTools/        ← this script lives here
      build.py
      platform.json
      templates/

USAGE
-----
  python PublishTools/build.py list
      Show all games and their readiness status.

  python PublishTools/build.py switch <game>
      Quick switch for simulator testing. Writes config/activeGame.lua only.
      Example: python PublishTools/build.py switch get10

  python PublishTools/build.py prepare <game> [ios|android]
      Full preparation for App Store / Play Store submission:
        1. Writes <game>/config/activeGame.lua
        2. Writes <game>/config/gameConfig.lua  (ad IDs, URLs, feature flags)
        3. Writes <game>/build.settings         (from template)
        4. Prints a publish-readiness checklist
      Example: python PublishTools/build.py prepare get10 ios

ADDING A NEW GAME
-----------------
  1. Add a new entry to PublishTools/platform.json  (set project_folder)
  2. Create <project_folder>/ inside Solar2DPuzzle/
  3. python PublishTools/build.py switch <game>  — start building
  4. python PublishTools/build.py prepare <game> ios  — before submitting
"""

import argparse
import json
import os
import sys
from datetime import datetime

# ── Paths ─────────────────────────────────────────────────────────────────────

SCRIPT_DIR    = os.path.dirname(os.path.abspath(__file__))   # .../PublishTools/
PLATFORM_ROOT = os.path.dirname(SCRIPT_DIR)                   # .../Solar2DPuzzle/
PLATFORM_JSON = os.path.join(SCRIPT_DIR, "platform.json")
TEMPLATE_DIR  = os.path.join(SCRIPT_DIR, "templates")
TEMPLATE_BUILD = os.path.join(TEMPLATE_DIR, "build.settings.template")

# ── Helpers ───────────────────────────────────────────────────────────────────

def load_platform():
    if not os.path.exists(PLATFORM_JSON):
        die(f"platform.json not found at: {PLATFORM_JSON}")
    with open(PLATFORM_JSON, "r") as f:
        return json.load(f)

def get_game(platform, game_key):
    games = platform.get("games", {})
    if game_key not in games:
        available = ", ".join(k for k in games if not k.startswith("_"))
        die(f"Unknown game '{game_key}'. Available: {available}")
    return games[game_key]

def game_dir(game):
    """Return absolute path to the game's Solar2D project folder."""
    folder = game.get("project_folder", "")
    if not folder:
        die("Game entry missing 'project_folder' in platform.json")
    return os.path.join(PLATFORM_ROOT, folder)

def write_file(path, content, label):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    rel = os.path.relpath(path, PLATFORM_ROOT)
    print(f"  [OK] Wrote {label}")
    print(f"       {rel}")

def die(msg):
    print(f"\n[ERROR] {msg}\n")
    sys.exit(1)

def is_placeholder(val):
    return isinstance(val, str) and "PLACEHOLDER" in val

def timestamp():
    return datetime.now().strftime("%Y-%m-%d %H:%M")

# ── Lua generators ────────────────────────────────────────────────────────────

def make_active_game_lua(game_key):
    return f'''\
-- AUTO-GENERATED by PublishTools/build.py — DO NOT EDIT MANUALLY
-- Run: python PublishTools/build.py switch {game_key}
-- Generated: {timestamp()}

return "{game_key}"
'''

def make_game_config_lua(game_key, game):
    ads  = game.get("ads",     {})
    urls = game.get("urls",    {})
    soc  = game.get("social",  {})
    feat = game.get("features",{})

    def lua_str(val):
        return f'"{val}"'

    def lua_bool(val):
        return "true" if val else "false"

    def lua_ad_pair(ios_key, android_key):
        return (f'{{ ios={lua_str(ads.get(ios_key, "PLACEHOLDER"))}, '
                f'android={lua_str(ads.get(android_key, "PLACEHOLDER"))} }}')

    return f'''\
-- =============================================================================
-- config/gameConfig.lua
-- AUTO-GENERATED by PublishTools/build.py — DO NOT EDIT MANUALLY
-- Game:      {game_key}  ({game.get("display_name","")})
-- Version:   {game.get("version","1.0.0")} (build {game.get("build_number",1)})
-- Generated: {timestamp()}
--
-- To update: edit PublishTools/platform.json, then run:
--   python PublishTools/build.py prepare {game_key} ios
-- =============================================================================

return {{

    -- ── Identity ──────────────────────────────────────────────────────────────
    ACTIVE_GAME  = {lua_str(game_key)},
    GAME_NAME    = {lua_str(game.get("display_name",""))},
    VERSION      = {lua_str(game.get("version","1.0.0"))},
    BUILD_NUMBER = {game.get("build_number", 1)},
    ENTRY_SCENE  = {lua_str(game.get("entry_scene","scenes.menu"))},

    -- ── URLs (update before App Store submission) ─────────────────────────────
    URLS = {{
        PRIVACY = {lua_str(urls.get("privacy",""))},
        TERMS   = {lua_str(urls.get("terms",""))},
        SUPPORT = {lua_str(urls.get("support",""))},
    }},

    -- ── Ad IDs (replace PLACEHOLDER values before enabling ads) ─────────────
    ADS = {{
        ADMOB_APP_ID    = {lua_ad_pair("admob_app_id_ios",    "admob_app_id_android")},
        BANNER_ID       = {lua_ad_pair("banner_id_ios",       "banner_id_android")},
        INTERSTITIAL_ID = {lua_ad_pair("interstitial_id_ios", "interstitial_id_android")},
        REWARDED_ID     = {lua_ad_pair("rewarded_id_ios",     "rewarded_id_android")},
    }},

    -- ── Feature flags ─────────────────────────────────────────────────────────
    FEATURES = {{
        ADS_ENABLED         = {lua_bool(feat.get("ads_enabled",         False))},
        IAP_ENABLED         = {lua_bool(feat.get("iap_enabled",         False))},
        ANALYTICS_ENABLED   = {lua_bool(feat.get("analytics_enabled",   False))},
        LEADERBOARD_ENABLED = {lua_bool(feat.get("leaderboard_enabled", False))},
    }},

    -- ── Social ────────────────────────────────────────────────────────────────
    SOCIAL = {{
        TWITTER  = {lua_str(soc.get("twitter",""))},
        FACEBOOK = {lua_str(soc.get("facebook",""))},
        WEBSITE  = {lua_str(soc.get("website",""))},
    }},
}}
'''

def make_build_settings(game_key, game):
    if not os.path.exists(TEMPLATE_BUILD):
        die(f"Template not found: {TEMPLATE_BUILD}")
    with open(TEMPLATE_BUILD, "r") as f:
        tpl = f.read()

    ads     = game.get("ads", {})
    exclude = game.get("exclude_from_build", [])
    patterns = ", ".join(f'"{d}/*"' for d in exclude) if exclude else ""

    replacements = {
        "{{GAME_KEY}}":           game_key,
        "{{DISPLAY_NAME}}":       game.get("display_name", ""),
        "{{BUNDLE_ID_IOS}}":      game.get("bundle_id_ios", ""),
        "{{BUNDLE_ID_ANDROID}}":  game.get("bundle_id_android", ""),
        "{{VERSION}}":            game.get("version", "1.0.0"),
        "{{BUILD_NUMBER}}":       str(game.get("build_number", 1)),
        "{{ADMOB_APP_ID_IOS}}":   ads.get("admob_app_id_ios", "PLACEHOLDER"),
        "{{EXCLUDE_PATTERNS}}":   patterns,
    }
    for k, v in replacements.items():
        tpl = tpl.replace(k, v)
    return tpl

# ── Checklist ─────────────────────────────────────────────────────────────────

def print_checklist(game_key, game):
    ads  = game.get("ads",       {})
    urls = game.get("urls",      {})
    feat = game.get("features",  {})
    app  = game.get("app_store", {})
    gdir = game_dir(game)

    issues   = []
    ok_items = []

    for key in ("privacy", "terms"):
        val = urls.get(key, "")
        if not val or "example.com" in val:
            issues.append(f"URL not set: urls.{key}  (needed for T&C screen + App Store)")
        else:
            ok_items.append(f"URL ok: {key}")

    for key in ("apple_id", "google_play_id", "apple_team_id"):
        val = app.get(key, "")
        if not val:
            issues.append(f"App Store field empty: app_store.{key}")
        else:
            ok_items.append(f"App Store {key}: {val}")

    for key in ("bundle_id_ios", "bundle_id_android"):
        val = game.get(key, "")
        if not val or "YOURCOMPANY" in val:
            issues.append(f"Bundle ID not set: {key}  (replace YOURCOMPANY)")
        else:
            ok_items.append(f"Bundle ID ok: {val}")

    if feat.get("ads_enabled"):
        for key in ("admob_app_id_ios", "admob_app_id_android",
                    "banner_id_ios", "banner_id_android",
                    "interstitial_id_ios", "interstitial_id_android"):
            if is_placeholder(ads.get(key, "")):
                issues.append(f"Ad ID missing: ads.{key}  (ads_enabled=true)")
    else:
        ok_items.append("Ads disabled — ad IDs not required yet")

    build_path = os.path.join(gdir, "build.settings")
    if os.path.exists(build_path):
        ok_items.append("build.settings exists")
    else:
        issues.append("build.settings not generated  (run prepare first)")

    icon_path = os.path.join(gdir, "assets", "icons")
    if os.path.isdir(icon_path):
        ok_items.append("Icons folder exists")
    else:
        issues.append("App icons missing: assets/icons/ folder not found")

    print()
    print(f"  ── Publish Checklist: {game.get('display_name', game_key)} ──")
    for item in ok_items:
        print(f"  [OK] {item}")
    if issues:
        print()
        for item in issues:
            print(f"  [!!] {item}")
        print()
        print(f"  {len(issues)} item(s) need attention before submitting.")
    else:
        print()
        print("  All checks passed — ready to build!")
    print()

# ── Commands ──────────────────────────────────────────────────────────────────

def cmd_list(platform):
    games = platform.get("games", {})
    print()
    print("  Solar2DPuzzle — Games")
    print()
    for key, game in games.items():
        if key.startswith("_"):
            continue
        status  = game.get("_status", "active")
        name    = game.get("display_name", key)
        ver     = game.get("version", "?")
        folder  = game.get("project_folder", "?")
        ads_on  = game.get("features", {}).get("ads_enabled", False)
        exists  = os.path.isdir(os.path.join(PLATFORM_ROOT, folder))
        exists_str = "exists" if exists else "FOLDER MISSING"
        print(f"  {key:20s}  {name:20s}  v{ver}  ads={'ON' if ads_on else 'off'}"
              f"  [{status}]  {folder}/ ({exists_str})")
    print()
    print("  Commands (run from Solar2DPuzzle/):")
    print("    python PublishTools/build.py switch <game>")
    print("    python PublishTools/build.py prepare <game> ios|android")
    print()

def cmd_switch(platform, game_key):
    game = get_game(platform, game_key)
    gdir = game_dir(game)
    print(f"\n  Switching to: {game.get('display_name', game_key)}\n")
    out = os.path.join(gdir, "config", "activeGame.lua")
    write_file(out, make_active_game_lua(game_key), "activeGame.lua")
    print()
    print(f"  Open {game.get('project_folder','?')}/ in Solar2D Simulator and press Cmd+R.")
    print()

def cmd_prepare(platform, game_key, target):
    game = get_game(platform, game_key)
    gdir = game_dir(game)
    name = game.get("display_name", game_key)
    print(f"\n  Preparing: {name}  [{target}]\n")

    write_file(os.path.join(gdir, "config", "activeGame.lua"),
               make_active_game_lua(game_key), "activeGame.lua")
    write_file(os.path.join(gdir, "config", "gameConfig.lua"),
               make_game_config_lua(game_key, game), "gameConfig.lua")
    write_file(os.path.join(gdir, "build.settings"),
               make_build_settings(game_key, game), "build.settings")

    print_checklist(game_key, game)

# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Solar2DPuzzle platform build manager",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("list", help="Show all games and their status")

    p_switch = sub.add_parser("switch", help="Quick switch for simulator")
    p_switch.add_argument("game", help="Game key  e.g. get10")

    p_prep = sub.add_parser("prepare", help="Full publish preparation")
    p_prep.add_argument("game",   help="Game key  e.g. get10")
    p_prep.add_argument("target", nargs="?", default="ios",
                        choices=["ios", "android", "both"],
                        help="Target platform (default: ios)")

    args = parser.parse_args()
    platform = load_platform()

    if args.command == "list":
        cmd_list(platform)
    elif args.command == "switch":
        cmd_switch(platform, args.game)
    elif args.command == "prepare":
        cmd_prepare(platform, args.game, args.target)

if __name__ == "__main__":
    main()
