-- =============================================================================
-- config/gameConfig.lua
-- AUTO-GENERATED by PublishTools/build.py — DO NOT EDIT MANUALLY
-- Game:      get10  (Get 10)
-- Version:   1.0.0 (build 1)
-- Generated: 2026-03-06 22:44
--
-- To update: edit PublishTools/platform.json, then run:
--   python PublishTools/build.py prepare get10 ios
-- =============================================================================

return {

    -- ── Identity ──────────────────────────────────────────────────────────────
    ACTIVE_GAME  = "get10",
    GAME_NAME    = "Get 10",
    VERSION      = "1.0.0",
    BUILD_NUMBER = 1,
    ENTRY_SCENE  = "scenes.menu",

    -- ── URLs (update before App Store submission) ─────────────────────────────
    URLS = {
        PRIVACY = "https://example.com/get10/privacy",
        TERMS   = "https://example.com/get10/terms",
        SUPPORT = "https://example.com/get10/support",
    },

    -- ── Ad IDs (replace PLACEHOLDER values before enabling ads) ─────────────
    ADS = {
        ADMOB_APP_ID    = { ios="PLACEHOLDER_ADMOB_APP_ID_IOS", android="PLACEHOLDER_ADMOB_APP_ID_ANDROID" },
        BANNER_ID       = { ios="PLACEHOLDER_BANNER_IOS", android="PLACEHOLDER_BANNER_ANDROID" },
        INTERSTITIAL_ID = { ios="PLACEHOLDER_INTERSTITIAL_IOS", android="PLACEHOLDER_INTERSTITIAL_ANDROID" },
        REWARDED_ID     = { ios="PLACEHOLDER_REWARDED_IOS", android="PLACEHOLDER_REWARDED_ANDROID" },
    },

    -- ── Feature flags ─────────────────────────────────────────────────────────
    FEATURES = {
        ADS_ENABLED         = false,
        IAP_ENABLED         = false,
        ANALYTICS_ENABLED   = false,
        LEADERBOARD_ENABLED = false,
    },

    -- ── Social ────────────────────────────────────────────────────────────────
    SOCIAL = {
        TWITTER  = "",
        FACEBOOK = "",
        WEBSITE  = "",
    },
}
